"""search_hist

Revision ID: 41d9dc09f6d1
Revises:
Create Date: 2025-12-14 12:03:06.867275

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = '41d9dc09f6d1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'search_history',
        sa.Column('query_type', sa.String(length=50), nullable=False),
        sa.Column('query', sa.String(length=50), nullable=False),
        sa.Column('result', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column('processing_time', sa.Float(), nullable=False),
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column(
            'created_at',
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text('now()'),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_search_history')),
        sa.UniqueConstraint('id', name=op.f('uq_search_history_id')),
    )
    op.create_index(
        op.f('ix_search_history_query_type'),
        'search_history',
        ['query_type'],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_search_history_query_type'), table_name='search_history')
    op.drop_table('search_history')
    # ### end Alembic commands ###
