"""search_hist_user

Revision ID: 851c74e1e6da
Revises: 41d9dc09f6d1
Create Date: 2025-12-14 13:13:12.860477

"""

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = '851c74e1e6da'
down_revision = '41d9dc09f6d1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'search_history', sa.Column('user', sa.String(length=50), nullable=True)
    )
    op.create_index(
        op.f('ix_search_history_user'), 'search_history', ['user'], unique=False
    )
    op.create_unique_constraint(op.f('uq_search_history_id'), 'search_history', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_search_history_id'), 'search_history', type_='unique')
    op.drop_index(op.f('ix_search_history_user'), table_name='search_history')
    op.drop_column('search_history', 'user')
    # ### end Alembic commands ###
