"""inference_hist

Revision ID: 9c30eb971b72
Revises:
Create Date: 2025-12-14 11:03:17.757540

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = '9c30eb971b72'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'infer_history',
        sa.Column('query_type', sa.String(length=50), nullable=False),
        sa.Column('query', sa.String(length=50), nullable=False),
        sa.Column('result', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column('processing_time', sa.Float(), nullable=False),
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column(
            'created_at',
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text('now()'),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_infer_history')),
        sa.UniqueConstraint('id', name=op.f('uq_infer_history_id')),
    )
    op.create_index(
        op.f('ix_infer_history_query_type'), 'infer_history', ['query_type'], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_infer_history_query_type'), table_name='infer_history')
    op.drop_table('infer_history')
    # ### end Alembic commands ###
